export default {
  BACKUP: 'Backup',
  RECEIVE: 'Receive',
  RECEIVED: 'Received',
  SEND: 'Send',
  SENT: 'Sent',
  ADD_NEW_WALLET: 'Add new wallet',
  SCAN_QR_CODE: 'Scan QR Code',
  COPY: 'Copy',
  TRANSACTIONS: 'Transactions',
  TOKEN: 'Token',
  ETHEREUM: 'Ethereum',
  PENDING: 'Pending',
  TITLE_SEND_SUCCESS: 'Your transfer is completed.',
  SUB_TITTLE_SEND_SUCCESS: 'The process may take up to some seconds. Please check your history for transaction status.',
  TEXT_VIEW_DETAIL: 'View Details',
  RETURN_WALLET: 'Return to wallet',
  CREATE_NEW_WALLET: 'Create a new wallet',
  CONFIRM: 'Confirm',
  SCAN: 'Scan',
  UNLOCK_YOUR_WALLET: 'Unlock Your Wallet',
  SETTING: 'Settings',
  COIN: 'Select Coin',
  SEND_TO: 'Send To',
  AMOUNT: 'Amount',
  GAS_LIMIT: 'Gas Limit',
  SLOW: 'Slow',
  NORMAL: 'Normal',
  FAST: 'Fast',
  PLEASE_BACK_UP: 'Please back up your wallet now',
  WE_HIGHLY_RECOMENC: 'We highly recommenc that you write down your mnemonic phrase on a piece of paper and keep it in safe place.',
  ATTENTION: 'Attention',
  THERE_IS_NO_WAY: 'There is no way to recover it once it is forgotten. Anyone with your mnemonic phrase can access your wallet and spend your asssets',
  ADD: 'Add',
  NAME: 'Name',
  COLOR: 'Color',
  SAVE: 'Save',
  IMPORT: 'Photos',
  PASTE_ADDRESS: 'Paste Address',
  titleRatingApp: 'Enjoying Starfish',
  desRatingApp: 'Rate us on the Google Play',
  ratingLater: 'Ask me later',
  cancel: 'Cancel',
  rating: 'Rate it',
  ADVANCE: 'Advance',
  DATA: 'Data',
  GAS_GWEI: 'Gas Gwei',
  GOT_IT: 'Got it!',
  DONE: 'Done',
  WARNING: 'WARNING!',
  BACKUP_DESCRIPTION: 'The Mnemonic is the account and PIN of your digital wallet. We never record your Mnemonic. Once it’s lost, there’s no way to recover your assets. Therefore, please backup your Mnemonic and keep the 12 Phrases in a safe place.',

  HIDE_SHOW_BALANCE_ID_SAVED: 'HIDE_SHOW_BALANCE_ID_SAVED',
  HIDE_SHOW_ESTIMATEBVALUE_ID_SAVED: 'HIDE_SHOW_ESTIMATEBVALUE_ID_SAVED',
  SECRET_WORK: '*****',
  CHOOSE_ADDRESS: 'Choose recipient',
  ADD_FROM_ALBUM: 'Add from album',

  INFURA_API_KEY: 'qMZ7EIind33NY9Azu836'
}
