const ScreenID = {
  App: 'App',
  AddContactScreen: 'AddContactScreen',
  AddPrivateKeyScreen: 'AddPrivateKeyScreen',
  AddressBookScreen: 'AddressBookScreen',
  BackupChooseKeywordScreen: 'BackupChooseKeywordScreen',
  BackupChooseSuccessScreen: 'BackupChooseSuccessScreen',
  BackupFinishScreen: 'BackupFinishScreen',
  BackupScreen: 'BackupScreen',
  BackupWalletScreen: 'BackupWalletScreen',
  BlindScreen: 'BlindScreen',
  ChooseAddressScreen: 'ChooseAddressScreen',
  ContactsElementScreen: 'ContactsElementScreen',
  CreateSuccessScreen: 'CreateSuccessScreen',
  CreateWalletScreen: 'CreateWalletScreen',
  DWebBrowserScreen: 'DWebBrowserScreen',
  EditYourWalletScreen: 'EditYourWalletScreen',
  HomeScreen: 'HomeScreen',
  ImportViaAddressScreen: 'ImportViaAddressScreen',
  ImportViaMnemonicScreen: 'ImportViaMnemonicScreen',
  ImportViaPrivateKeyScreen: 'ImportViaPrivateKeyScreen',
  ImportWalletScreen: 'ImportWalletScreen',
  ListWalletScreen: 'ListWalletScreen',
  NetworkScreen: 'NetworkScreen',
  PrivacyPolicyWebView: 'PrivacyPolicyWebView',
  ReceiveScreen: 'ReceiveScreen',
  ScanQRCodeScreen: 'ScanQRCodeScreen',
  SelectedCoinScreen: 'SelectedCoinScreen',
  SendTransactionScreen: 'SendTransactionScreen',
  SettingScreen: 'SettingScreen',
  TokenScreen: 'TokenScreen',
  TransactionDetailInfo: 'TransactionDetailInfo',
  TransactionDetailScreen: 'TransactionDetailScreen',
  TxHashWebView: 'TxHashWebView',
  UnlockScreen: 'UnlockScreen',
  PopupCustom: 'PopupCustom',

  NormalPopup: 'NormalPopup',
  BinaryPopup: 'BinaryPopup',

  EnterNameScreen: 'EnterNameScreen',
  ConfirmScreen: 'ConfirmScreen',
  AddressInputScreen: 'AddressInputScreen',

  CustomToastTop: 'CustomToastTop'
}

export default ScreenID
